name: Build video
on: [push]
jobs:
  build_video:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          sudo apt install -y sox
          pip install requests
          pip install sox
          npm install puppeteer
          mkdir json thumbnails frames mp3
      - name: Python preprocessing
        run: |
          python preprocess.py https://www.oyez.org/cases/2023/22-340
      - name: Build video
        run: |
          python -m http.server 8002 &
          node screenshot.js 63561