name: Build video
on: [push]
jobs:
  build_video:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Download YouTube credential
        run: |
          curl -o credentials.json ${{ secrets.CREDENTIAL_URL }}
      - name: Install dependencies
        run: |
          sudo apt install -y sox libsox-fmt-mp3 ffmpeg
          pip install requests sox b2sdk pillow google-api-python-client google-auth google-auth-oauthlib
          npm install puppeteer
          mkdir json thumbnails frames videos
      - name: Python preprocessing
        run: |
          python preprocess.py https://www.oyez.org/cases/2023/22-340
      - name: Node screenshots
        run: |
          python -m http.server 8002 &
          node screenshot.js
      - name: Encode video
        run: |
          python build-video.py
      - name: Upload video
        env:
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
          B2_APP_KEY_ID: ${{ secrets.B2_APP_KEY_ID }}
          YT_DEV_KEY: ${{ secrets.YT_DEV_KEY }}
        run: |
          python upload-video.py
        # run: |
        #   curl --silent --upload-file thumbnails/63561.png --user f0146955:${{ secrets.ftp_password }} ftp://w008ef9a.kasserver.com
        #   curl --silent --upload-file frames/63561/frame-1.png --user f0146955:${{ secrets.ftp_password }} ftp://w008ef9a.kasserver.com