name: Build video
on: [push]
jobs:
  build_video:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          sudo apt install -y sox libsox-fmt-mp3 ffmpeg
          pip install requests
          pip install sox
          npm install puppeteer
          mkdir json thumbnails frames mp3
      # - name: Download and Install Myriad Pro font
      #   run: |
      #     curl -L -o myriadpro.zip "${{ secrets.FONT_ZIP_URL }}"
      #     unzip myriadpro.zip -d myriadpro
      #     sudo mkdir -p /usr/local/share/fonts/myriadpro
      #     sudo mv myriadpro/*.otf /usr/local/share/fonts/myriadpro/
      #     sudo fc-cache -f -v
      - name: Python preprocessing
        run: |
          python preprocess.py https://www.oyez.org/cases/2023/22-340
      - name: Build video
        run: |
          python -m http.server 8002 &
          node screenshot.js 63561
      - name: Push file to server
        run: curl --silent --upload-file thumbnails/63561.png --user f0146955:${{ secrets.ftp_password }} ftp://w008ef9a.kasserver.com